#!/bin/bash

# Menu options
menu_options=(
"Create a new file"
"Delete a file"
"List files in a directory"
"Exit"
)

# Display menu
while true; do
  echo "Menu:"
  select choice in "${menu_options[@]}"; do
    case $choice in
      "Create a new file")
        # Script for creating a new file
        echo "Enter filename: "
        read filename        		
		if [ -f "$filename" ]; then
         #rm "$filename"
          echo "File '$filename' already exists."
		else
			touch "$filename"
			#echo "File '$filename' created successfully."
			if [ $? -eq 0 ]; then
			  echo "File '$filename' created successfully."
			else
			  echo "Error creating file '$filename'."
			fi
			break
		fi
		#break	

        ;;
      "Delete a file")
        # Script for deleting a file
        echo "Enter filename to delete: "
        read filename
        if [ -f "$filename" ]; then
          rm "$filename"
          echo "File '$filename' deleted successfully."
        else
          echo "File '$filename' not found."
        fi
        break
        ;;
      "List files in a directory")
        # Script for listing files in a directory
        ls
        break
        ;;
      "Exit")
        echo "Exiting..."
        exit 0
        ;;
      *)
        echo "Invalid choice. Please choose a number between 1 and 4."
        ;;
    esac
  done
done
